version: '3.5'
# Use this script for running up a standalone Geth private network, accessed
# through localhost. It is a complete file, and not an override.
services:
  bootnode:
    image: ethereum/client-go:alltools-stable
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
    networks:
      geth_network:
        # fixed IP because the enode can't use a dns name
        ipv4_address: 172.16.239.10
    command:
      bootnode --nodekey=setup/node.key

  blockchain1:
    image: ethereum/client-go:stable
    ports:
      - 8546:8546
      - 8545:8545
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
      - type: bind
        source: ./volumes/geth1-chain
        target: /data
    networks:
      geth_network:
    entrypoint: /setup/entrypoint.sh
    command:
      --http --http.addr 0.0.0.0 --http.port 8545 --http.vhosts * --http.corsdomain * --http.api eth,net,web3,admin,txpool,personal --ws.port 8546 --ws --ws.origins * --ws.addr 0.0.0.0 --verbosity 3


  blockchain-miner1:
    image: ethereum/client-go:stable
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
      - type: bind
        source: ./volumes/geth-miner-chain1
        target: /data
      - type: bind
        source: ./volumes/dag1
        target: /dag
    networks:
      geth_network:
    entrypoint: /setup/entrypoint.sh
    command:
      --http --http.addr 0.0.0.0 --http.port 8545 --http.vhosts * --http.corsdomain * --http.api eth,net,web3,admin,txpool,personal --ws.port 8546 --ws --ws.origins * --ws.addr 0.0.0.0 --verbosity 3 --mine

networks:
  geth_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1
